### ISSUE TITLE
Bug?: Vertical positioning/alignment

### ISSUE THREAD

**Issue by avirosso** [liamcain/obsidian-lapel#9] opened 2022-03-28 08:11 UTC
The vertical positioning/alignment is not working - see screenshots standard theme and minimal theme (no userdefined css snippets)

Standard theme:
![Standard Theme](https://user-images.githubusercontent.com/95497044/160354763-f46f23e0-d446-410c-8b69-e1ca320a26e9.png)

Minimal theme:
![Minimal Theme](https://user-images.githubusercontent.com/95497044/160354782-ef43e500-9966-4c28-96df-319c3db6cbb2.png)

**Comment by liamcain** [comment] 2022-03-28 12:56
Hi, what version of Obsidian are you using? Do you have any additional plugins installed that could be affecting the styling?

I am unable to reproduce the issue in an empty vault with nothing but the plugin installed, so there must be something else interacting with the plugin. I notice the second screenshot has a line under the headline which doesn't happen by default. If you have any additional configuration set in the Style Settings plugin for example, could you provide those as well?

**Comment by avirosso** [comment] 2022-03-28 14:59
Hi, thanks for the detailed answer! I tested and figured out that probably it's caused by the 'breadcrumbs'-Plugin: The plugin renders the "Trail-View" at the top of a page, so the whole content/text (but NOT the lapel markers) 'slips down'. Is there a solution for this kind of problem (for me - and maybe others - the breadcrumbs plugin is indispensable) ...

**Comment by liamcain** [comment] 2024-07-17 18:40
This is a breadcrumbs issue so I'll close this. It looks like the issue was reported and will be fixed in Breadcrumbs v4 (https://github.com/SkepticMystic/breadcrumbs/issues/450)

**Closed by liamcain** 2024-07-17 18:40 UTC
